name    'inkblot/riakcs'
version '1.1.1'
source  'git://github.com/inkblot/puppet-riakcs'
author  'inkblot'
license 'Apache 2.0'
summary 'RiakCS'
description 'A Puppet module for setting up RiakCS'
project_page 'https://github.com/inkblot/puppet-riakcs'

dependency 'inkblot/riak', '>= 1.0.0'
