#!/usr/bin/env ruby
# ex: syntax=ruby si ts=4 sw=4 et

require 'net/http'
require 'json'
require 'uri'
require 'yaml'
require 'tempfile'
require 'fileutils'

def create_admin_user(name, email, ipaddress, port)
    uri = URI.parse("http://#{ipaddress}:#{port}/riak-cs/user")
    request = Net::HTTP::Post.new(uri.request_uri, 'Content-Type' => 'application/json')
    request.body = {
        'email' => email,
        'name' => name
    }.to_json
    response = Net::HTTP.new(uri.host, uri.port).start { |http| http.request(request) }
    json = JSON.parse(response.body)
    [ json['key_id'], json['key_secret'] ]
end

admin_key, admin_secret = create_admin_user('admin user', ARGV[0], ARGV[1], 8080)
IO.write('/etc/facter/facts.d/riakcs.yaml', {
    'riakcs_admin_key' => admin_key,
    'riakcs_admin_secret' => admin_secret
}.to_yaml)

temp = Tempfile.new('app.config')
File.open('/etc/riak-cs/app.config', 'r') do |file|
    file.each_line do |line|
        case line
		    when /{anonymous_user_creation, true},/
			    temp.puts "              {anonymous_user_creation, false},\n"
		    when /{admin_key, "admin-key"},/
			    temp.puts "              {admin_key, \"#{admin_key}\"},\n"
            when /{admin_secret, "admin-secret"},/
			    temp.puts "              {admin_secret, \"#{admin_secret}\"},\n"
		    else
			    temp.puts line
        end
    end
end
temp.close
FileUtils.cp(temp.path, '/etc/riak-cs/app.config')
FileUtils.chown('riakcs', 'riak', '/etc/riak-cs/app.config')
FileUtils.chmod(0644, '/etc/riak-cs/app.config')
